### ISSUE TITLE
خطأ في أول سطر في كل الملفات 

### ISSUE THREAD

**Issue by mohamed-ali** [abdelrahmaan/Hadith-Data-Sets#1]
<div dir="rtl">
السلام عليكم، شكرا على الجهد الطيب في جمع الأحاديث. 

هناك خطأ في جميع الملفات حيث أنها تبدأ بكلمة Sahih Bukhari رغم إختلاف المصادر
</div>

**Comment by abdelrahmaan** [comment]
وعليكم السلام
الله يكرمك
تمام .. جزاك الله خيراً
